### ISSUE TITLE
Xcode 실행 오류로 인한 프로젝트 파일 이동 및 dev 브랜치를 메인 브랜치로 수정

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#39]
## 💡 issue
Xcode 빌드 이후 실행 오류 발생
info.plist 파일로 인한 문제로 추정(?)
프로젝트 파일 dev 브랜치로 새롭게 이동

## 📝 todo
- [ ]  문제없었던 브랜치에서 파일 추가해 dev 브랜치에 pull request하기

**Comment by gom1n** [comment]
🎉👊
